﻿FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
﻿# Ustawienie środowiska pracy
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Instalacja ChromeDriver
RUN apt-get update -y && apt-get install -y wget unzip
RUN wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip -d /usr/local/bin/
RUN rm chromedriver_linux64.zip

# Kopiowanie projektu i jego przywracanie
COPY *.csproj ./
RUN dotnet restore