FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Kopiowanie projektu i jego przywracanie
COPY *.csproj ./
RUN dotnet restore

# Kopiowanie reszty plików i budowanie aplikacji
COPY . ./
RUN dotnet publish -c Release -o out

# Uruchomienie testów
FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "test", "--logger:trx"]
